In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os 

dataset = pd.read_csv(os.getcwd() + "/Restaurant_Reviews.tsv", delimiter='\t', quoting=3)

In [2]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import CountVectorizer

# nltk.download('stopwords')

In [3]:
corpus = []
ps = PorterStemmer()
# preprocessing the data and stemming
for i in range(0, 1000):    
    review = re.sub('[^a-zA-Z]', ' ', dataset['Review'][i]) # get just the words
    review = review.lower()                                 # lower the case
    review = review.split()                                 # make list of words

    # stem and remove stopwords
    review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    corpus.append(' '.join(review))                   # add review

cv = CountVectorizer(max_features=1500)
X = cv.fit_transform(corpus).toarray()
y = dataset.iloc[:,1].values

In [26]:
# Naive Bayes
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

# Fitting the classifier to the Training set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix
nb_cm =  confusion_matrix(y_test, y_pred)

In [55]:
# random forest
# Fitting the classifier to the Training set
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=400, criterion='entropy', random_state=0)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

rf_cm = confusion_matrix(y_test, y_pred)


In [31]:
from sklearn.svm import SVC
classifier = SVC(kernel='rbf', random_state=0)
classifier.fit(X_train, y_train)
 
y_pred = classifier.predict(X_test)

svm_cm = confusion_matrix(y_test, y_pred)

In [56]:
print("Naive bayes: ", '\n',nb_cm, '\n','\nRandom Forest:', '\n', rf_cm, '\n', '\nSVM:', '\n', svm_cm )

Naive bayes:  
 [[55 42]
 [12 91]] 
 
Random Forest: 
 [[88  9]
 [47 56]] 
 
SVM: 
 [[90  7]
 [46 57]]
